spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.110/sell?useUnicode=true&characterEncoding=utf8&useSSL=true
  jpa:
    show-sql: true